CREATE SEQUENCE "game_seq" MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE "company_seq" MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE "platform" MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE "game_company_seq" MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE "game_platform_seq" MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE "basket_seq" MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE "customer_seq" MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE "static_data_seq" MINVALUE 1 INCREMENT BY 1;