CREATE OR REPLACE FUNCTION GAME_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."id":=NEXTVAL('"game_seq"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION COMPANY_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."id":=NEXTVAL('"company_seq"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION PLATFORM_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."id":=NEXTVAL('"platform_seq"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION GAME_COMPANY_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."id":=NEXTVAL('"game_company_seq"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION GAME_PLATFORM_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."id":=NEXTVAL('"game_platform_seq"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

  CREATE OR REPLACE FUNCTION STATIC_DATA_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."id":=NEXTVAL('"static_data_seq"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION BASKET_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."id":=NEXTVAL('"basket_seq"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION CUSTOMER_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."id":=NEXTVAL('"customer_seq"');
   RETURN NEW;
 END;
 